import SEO from "@/components/SEO";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const PrivacyPolicy = () => {
  return (
    <>
      <SEO
        title="Privacy Policy"
        description="Privacy Policy for PathOnAI.org - Learn how we collect, use, and protect your information."
      />
      <div className="min-h-screen bg-white dark:bg-gray-900 p-4 pt-24">
        <div className="max-w-4xl mx-auto">
          <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl mb-8 text-black dark:text-white">
            Privacy Policy
          </h1>
          
          <Card className="mb-8 shadow-md">
            <CardContent className="pt-6">
              <p className="text-sm text-gray-500 dark:text-gray-400">Last updated: March 8, 2025</p>
            </CardContent>
          </Card>
          
          <Card className="mb-8 shadow-md">
            <CardHeader>
              <CardTitle>Introduction</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="mb-4">
                PathOnAI.org (&ldquo;we&rdquo;, &ldquo;our&rdquo;, or &ldquo;us&rdquo;) is committed to protecting your privacy. This Privacy Policy explains how we collect, use, 
                and share information about you when you visit our website at https://pathonai.org (the &ldquo;Site&rdquo;).
              </p>
              <p>
                By using our Site, you agree to the collection and use of information in accordance with this policy.
              </p>
            </CardContent>
          </Card>
          
          <Card className="mb-8 shadow-md">
            <CardHeader>
              <CardTitle>Information We Collect</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="mb-4">
                We collect information about you in the following ways:
              </p>
              
              <h3 className="text-lg font-semibold mt-4 mb-2">Information you provide to us directly:</h3>
              <p className="mb-4">We may collect information if you contact us or subscribe to our newsletter.</p>
              
              <h3 className="text-lg font-semibold mt-4 mb-2">Information we collect automatically:</h3>
              <p className="mb-2">When you visit our Site, we automatically collect certain information about your device and your visit, including:</p>
              <ul className="list-disc pl-6 mb-4 space-y-1">
                <li>Log information (such as IP address, browser type, referring/exit pages)</li>
                <li>Device information (such as device type, operating system)</li>
                <li>Usage information (such as pages viewed, time spent on pages)</li>
              </ul>
            </CardContent>
          </Card>
          
          <Card className="mb-8 shadow-md">
            <CardHeader>
              <CardTitle>Google Analytics</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="mb-4">
                We use Google Analytics, a web analytics service provided by Google LLC (&ldquo;Google&rdquo;), to help us understand how users 
                engage with our Site. Google Analytics uses cookies and similar technologies to collect and analyze information about your 
                use of the Site.
              </p>
              <p className="mb-4">
                The information generated by Google Analytics about your use of our Site (including your IP address) may be transmitted to 
                and stored by Google on servers in the United States or other countries. Google uses this information to evaluate your use of 
                the Site, compile reports on website activity, and provide other services related to website activity and internet usage.
              </p>
              <p className="mb-4">
                Google may also transfer this information to third parties where required to do so by law, or where such third parties process 
                the information on Google&apos;s behalf.
              </p>
              <p>
                You can opt-out of Google Analytics by installing the <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer" className="text-blue-600 dark:text-blue-400 hover:underline">Google Analytics Opt-out Browser Add-on</a>.
              </p>
            </CardContent>
          </Card>
          
          <Card className="mb-8 shadow-md">
            <CardHeader>
              <CardTitle>How We Use Your Information</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="mb-2">
                We use the information we collect to:
              </p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Provide, maintain, and improve our Site</li>
                <li>Understand and analyze how you use our Site</li>
                <li>Develop new products, services, features, and functionality</li>
                <li>Communicate with you about our services, including responding to your inquiries</li>
                <li>Monitor and analyze trends, usage, and activities in connection with our Site</li>
              </ul>
            </CardContent>
          </Card>
          
          <Card className="mb-8 shadow-md">
            <CardHeader>
              <CardTitle>Cookies</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="mb-4">
                Cookies are small text files that are placed on your device when you visit a website. We use cookies to:
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-1">
                <li>Remember your preferences and settings</li>
                <li>Understand how you interact with our Site</li>
                <li>Analyze and improve our Site</li>
              </ul>
              <p>
                Most web browsers allow you to control cookies through their settings preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience.
              </p>
            </CardContent>
          </Card>
          
          <Card className="mb-8 shadow-md">
            <CardHeader>
              <CardTitle>Data Retention</CardTitle>
            </CardHeader>
            <CardContent>
              <p>
                We will retain your information for as long as necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer retention period is required or permitted by law.
              </p>
            </CardContent>
          </Card>
          
          <Card className="mb-8 shadow-md">
            <CardHeader>
              <CardTitle>Your Rights</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="mb-4">
                Depending on your location, you may have certain rights regarding your personal information, such as:
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-1">
                <li>The right to access the personal information we hold about you</li>
                <li>The right to request correction or deletion of your personal information</li>
                <li>The right to restrict or object to our processing of your personal information</li>
                <li>The right to data portability</li>
              </ul>
              <p>
                To exercise these rights, please contact us using the information provided below.
              </p>
            </CardContent>
          </Card>
          
          <Card className="mb-8 shadow-md">
            <CardHeader>
              <CardTitle>Changes to This Privacy Policy</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="mb-4">
                We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the &ldquo;Last updated&rdquo; date.
              </p>
              <p>
                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
              </p>
            </CardContent>
          </Card>
          
          <Card className="mb-8 shadow-md">
            <CardHeader>
              <CardTitle>Contact Us</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="mb-4">
                If you have any questions about this Privacy Policy, please contact us at:
              </p>
              <p>
                <a href="mailto:info@pathonai.org" className="text-blue-600 dark:text-blue-400 hover:underline">info@pathonai.org</a>
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </>
  );
};

export default PrivacyPolicy; 